// This file was generated by the PolyShim library.
// <auto-generated/>

// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
internal static partial class PolyfillExtensions;
