// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
internal static partial class PolyfillExtensions;
