// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NETCOREAPP2_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD && !NETSTANDARD2_1_OR_GREATER)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;

internal static partial class PolyfillExtensions
{
    extension(Path)
    {
// Can only detect platform on .NET Standard 1.3+
#if !NETSTANDARD || NETSTANDARD1_3_OR_GREATER
        // https://learn.microsoft.com/dotnet/api/system.io.path.getrelativepath
        public static string GetRelativePath(string relativeTo, string path)
        {
            var pathStringComparison = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
                ? StringComparison.OrdinalIgnoreCase
                : StringComparison.Ordinal;

            var basePathSegments = relativeTo.Split(
                Path.DirectorySeparatorChar,
                Path.AltDirectorySeparatorChar
            );

            var pathSegments = path.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

            var commonSegmentsCount = 0;
            for (var i = 0; i < basePathSegments.Length && i < pathSegments.Length; i++)
            {
                if (!string.Equals(basePathSegments[i], pathSegments[i], pathStringComparison))
                    break;

                commonSegmentsCount++;
            }

            return string.Join(
                Path.DirectorySeparatorChar.ToString(),
                Enumerable
                    .Repeat("..", basePathSegments.Length - commonSegmentsCount)
                    .Concat(pathSegments.Skip(commonSegmentsCount)).ToArray()
            );
        }
#endif
    }
}
#endif
