// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NETCOREAPP2_0_OR_GREATER) || (NETSTANDARD && !NETSTANDARD2_0_OR_GREATER)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System;
using System.Reflection;

internal static partial class PolyfillExtensions
{
    extension(Type type)
    {
        // https://learn.microsoft.com/dotnet/api/system.type.isassignablefrom
        public bool IsAssignableFrom(Type otherType) =>
            type.GetTypeInfo().IsAssignableFrom(otherType.GetTypeInfo());

        // https://learn.microsoft.com/dotnet/api/system.type.issubclassof
        public bool IsSubclassOf(Type otherType)
        {
            var currentType = type;

            if (currentType == otherType)
                return false;

            while (currentType != null)
            {
                if (currentType == otherType)
                    return true;

                currentType = currentType.GetTypeInfo().BaseType;
            }

            return false;
        }
    }
}
#endif
