// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NET6_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System;

internal static partial class PolyfillExtensions
{
    extension(Math)
    {
        // https://learn.microsoft.com/dotnet/api/system.math.clamp#system-math-clamp(system-intptr-system-intptr-system-intptr)
        public static IntPtr Clamp(IntPtr value, IntPtr min, IntPtr max)
        {
            if (value.ToInt64() < min.ToInt64())
                return min;

            if (value.ToInt64() > max.ToInt64())
                return max;

            return value;
        }
    }
}
#endif