// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NET6_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System;

internal static partial class PolyfillExtensions
{
    private static readonly Random _sharedRandom = new();

    extension(Random)
    {
        // https://learn.microsoft.com/dotnet/api/system.random.shared
        public static Random Shared => _sharedRandom;
    }
}
#endif