// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NET6_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System;

internal static partial class PolyfillExtensions
{
    extension(string str)
    {
        // https://learn.microsoft.com/dotnet/api/system.string.replacelineendings#system-string-replacelineendings(system-string)
        public string ReplaceLineEndings(string replacementText) =>
            str.Replace("\r\n", "\n", StringComparison.Ordinal)
                .Replace("\r", "\n", StringComparison.Ordinal)
                .Replace("\n", replacementText, StringComparison.Ordinal);

        // https://learn.microsoft.com/dotnet/api/system.string.replacelineendings#system-string-replacelineendings
        public string ReplaceLineEndings() =>
            str.ReplaceLineEndings(Environment.NewLine);
    }
}
#endif
