// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NETCOREAPP3_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System.IO;

internal static partial class PolyfillExtensions
{
    extension(Path)
    {
        // https://learn.microsoft.com/dotnet/api/system.io.path.endsindirectoryseparator#system-io-path-endsindirectoryseparator(system-string)
        public static bool EndsInDirectorySeparator(string path)
        {
            if (string.IsNullOrEmpty(path))
                return false;

            var lastChar = path[^1];

#if !NETSTANDARD || NETSTANDARD1_3_OR_GREATER
            return lastChar == Path.DirectorySeparatorChar || lastChar == Path.AltDirectorySeparatorChar;
#else
            return lastChar is '\\' or '/';
#endif
        }

        // https://learn.microsoft.com/dotnet/api/system.io.path.trimendingdirectoryseparator#system-io-path-trimendingdirectoryseparator(system-string)
        public static string TrimEndingDirectorySeparator(string path)
        {
            if (string.IsNullOrEmpty(path))
                return path;

            var endIndex = path.Length;
            while (endIndex > 0)
            {
                var lastChar = path[endIndex - 1];

#if !NETSTANDARD || NETSTANDARD1_3_OR_GREATER
                if (lastChar != Path.DirectorySeparatorChar && lastChar != Path.AltDirectorySeparatorChar)
#else
                if (lastChar is not '\\' and not '/')
#endif
                {
                    break;
                }

                endIndex--;
            }

            return path[..endIndex];
        }
    }
}
#endif