// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETFRAMEWORK && !NET40_OR_GREATER)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System.IO;
using System.Linq;

internal static partial class PolyfillExtensions
{
    extension(Path)
    {
        // https://learn.microsoft.com/dotnet/api/system.io.path.combine#system-io-path-combine(system-string())
        public static string Combine(params string[] paths) =>
            paths.Aggregate(Path.Combine);
    }
}
#endif