// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETFRAMEWORK && !NET40_OR_GREATER)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System.Diagnostics.CodeAnalysis;

namespace System.Runtime.Versioning;

// https://learn.microsoft.com/dotnet/api/system.runtime.versioning.targetframeworkattribute
[AttributeUsage(AttributeTargets.Assembly)]
[ExcludeFromCodeCoverage]
internal class TargetFrameworkAttribute(string frameworkName) : Attribute
{
    public string FrameworkName { get; } = frameworkName;

    public string? FrameworkDisplayName { get; set; }
}
#endif