// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NET9_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System.Collections.Generic;

namespace System.Linq;

internal static partial class PolyfillExtensions
{
    extension<T>(IEnumerable<T> source)
    {
        // https://learn.microsoft.com/dotnet/api/system.linq.enumerable.index
        public IEnumerable<(int index, T value)> Index() =>
            source.Select((value, index) => (index, value));

        // https://learn.microsoft.com/dotnet/api/system.linq.enumerable.countby
        public IEnumerable<KeyValuePair<TKey, int>> CountBy<TKey>(Func<T, TKey> keySelector,
            IEqualityComparer<TKey>? comparer = null
        )
            where TKey : notnull
        {
            var counts = new Dictionary<TKey, int>(comparer);

            foreach (var item in source)
            {
                var key = keySelector(item);
                counts[key] = counts.TryGetValue(key, out var count) ? count + 1 : 1;
            }

            return counts;
        }

        // https://learn.microsoft.com/dotnet/api/system.linq.enumerable.aggregateby#system-linq-enumerable-aggregateby-3(system-collections-generic-ienumerable((-0))-system-func((-0-1))-system-func((-1-2))-system-func((-2-0-2))-system-collections-generic-iequalitycomparer((-1)))
        public IEnumerable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TKey,
            TAccumulate
        >(Func<T, TKey> keySelector,
            Func<TKey, TAccumulate> seedSelector,
            Func<TAccumulate, T, TAccumulate> accumulator,
            IEqualityComparer<TKey>? keyComparer = null
        )
            where TKey : notnull
        {
            var aggregates = new Dictionary<TKey, TAccumulate>(keyComparer);

            foreach (var item in source)
            {
                var key = keySelector(item);

                aggregates[key] = accumulator(
                    aggregates.TryGetValue(key, out var aggregate) ? aggregate : seedSelector(key),
                    item
                );
            }

            return aggregates;
        }

        // https://learn.microsoft.com/dotnet/api/system.linq.enumerable.aggregateby#system-linq-enumerable-aggregateby-3(system-collections-generic-ienumerable((-0))-system-func((-0-1))-2-system-func((-2-0-2))-system-collections-generic-iequalitycomparer((-1)))
        public IEnumerable<KeyValuePair<TKey, TAccumulate>> AggregateBy<TKey,
            TAccumulate
        >(Func<T, TKey> keySelector,
            TAccumulate seed,
            Func<TAccumulate, T, TAccumulate> accumulator,
            IEqualityComparer<TKey>? keyComparer = null
        )
            where TKey : notnull =>
            source.AggregateBy(keySelector, _ => seed, accumulator, keyComparer);
    }
}
#endif
