// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NET5_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System;
using System.Runtime.InteropServices;

internal static partial class PolyfillExtensions
{
    extension(OperatingSystem)
    {
// Can only detect the OS on .NET Standard 2.0+ and .NET Core App 2.0+
#if (!NETSTANDARD || NETSTANDARD2_0_OR_GREATER) && (!NETCOREAPP || NETCOREAPP2_0_OR_GREATER)
        // https://learn.microsoft.com/dotnet/api/system.operatingsystem.isfreebsd
        public static bool IsFreeBSD() => RuntimeInformation.IsOSPlatform(OSPlatform.FreeBSD);

        // https://learn.microsoft.com/dotnet/api/system.operatingsystem.islinux
        public static bool IsLinux() => RuntimeInformation.IsOSPlatform(OSPlatform.Linux);

        // https://learn.microsoft.com/dotnet/api/system.operatingsystem.isosx
        public static bool IsMacOS() => RuntimeInformation.IsOSPlatform(OSPlatform.OSX);

        // https://learn.microsoft.com/dotnet/api/system.operatingsystem.iswindows
        public static bool IsWindows() => RuntimeInformation.IsOSPlatform(OSPlatform.Windows);

        // https://learn.microsoft.com/dotnet/api/system.operatingsystem.iswindowsversionatleast
        public static bool IsWindowsVersionAtLeast(int major, int minor = 0, int build = 0, int revision = 0)
        {
            if (!IsWindows())
                return false;

            var version = Environment.OSVersion.Version;

            if (version.Major != major)
                return version.Major > major;

            if (version.Minor != minor)
                return version.Minor > minor;

            if (version.Build != build)
                return version.Build > build;

            return version.Revision >= revision;
        }
#endif
    }
}
#endif