// The following comment is required to instruct analyzers to skip this file
// <auto-generated/>

#if (NETCOREAPP && !NET5_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System;
using System.Reflection;

internal static partial class PolyfillExtensions
{
    extension(Type type)
    {
        // https://learn.microsoft.com/dotnet/api/system.type.isassignableto
        public bool IsAssignableTo(Type? otherType) =>
            otherType?.IsAssignableFrom(type) == true;
    }
}
#endif
