// This file was generated by the PolyShim library.
// <auto-generated/>

#if (NETCOREAPP && !NET7_0_OR_GREATER) || (NETFRAMEWORK) || (NETSTANDARD)
#nullable enable
// ReSharper disable RedundantUsingDirective
// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart

using System.Diagnostics.CodeAnalysis;

namespace System.Runtime.CompilerServices;

// https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.requiredmemberattribute
[AttributeUsage(
    AttributeTargets.Class
        | AttributeTargets.Field
        | AttributeTargets.Property
        | AttributeTargets.Struct,
    Inherited = false
)]
[ExcludeFromCodeCoverage]
internal class RequiredMemberAttribute : Attribute;
#endif
